conjc('alors', '0', 'alors', '').
conjc('car', '0', 'car', '').
conjc('donc', '0', 'donc', '').
conjc('et', '0', 'et', '').
conjc('mais', '0', 'mais', '').
conjc('ni', '0', 'ni', '').
conjc('or', '0', 'or', '').
conjc('ore', '0', 'ore', '').
conjc('ou', '0', 'ou', '').
conjc('puis', '0', 'puis', '').
